require("oil").setup({ view_options = { show_hidden = true } })
require("plugins.snacks")
require("plugins.tiny-inline-diagnostic")
require("plugins.rose-pine")

-- mini
require("plugins.icons")
require("plugins.clue")
require("plugins.hipatterns")
require("mini.basics").setup({options = { extra_ui = true }, mappings = { windows = true }})
require("mini.git").setup()
require("mini.diff").setup()
require("mini.surround").setup()
require("mini.pairs").setup()
require("mini.bracketed").setup()
require("mini.statusline").setup()
require("mini.jump").setup()
require("mini.jump2d").setup()
require("mini.notify").setup()
