hs.hotkey.bind(CA, "S", function()
    local osa = 'tell application "Safari"\nmake new document\nactivate\nend tell'
    hs.execute("osascript -e '" .. osa .. "'")
end)

hs.hotkey.bind(SA, "S", function()
    hs.application.launchOrFocus("Safari")
end)
hs.hotkey.bind(SA, "C", function()
    hs.application.launchOrFocus("Visual Studio Code")
end)
hs.hotkey.bind(SA, "N", function()
    hs.application.launchOrFocus("Notes")
end)
hs.hotkey.bind(SA, "P", function()
    hs.application.launchOrFocus("Notion")
end)
hs.hotkey.bind(SA, "M", function()
    hs.application.launchOrFocus("Music")
end)
hs.hotkey.bind(SA, "E", function()
    hs.application.launchOrFocus("Mail")
end)
hs.hotkey.bind(SA, "T", function()
    hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind(SA, "V", function()
    hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind(SA, "F", function()
    hs.application.launchOrFocus("Finder")
end)
hs.hotkey.bind(SA, "A", function()
    hs.application.launchOrFocus("Preview")
end)
