hs.hotkey.bind(SA, "S", function()
    local osa = 'tell application "Safari"\nmake new document\nactivate\nend tell'
    hs.execute("osascript -e '" .. osa .. "'")
end)

hs.hotkey.bind("Alt", "S", function()
    hs.application.launchOrFocus("Safari")
end)
hs.hotkey.bind("alt", "N", function()
    hs.application.launchOrFocus("Notes")
end)
hs.hotkey.bind("alt", "O", function()
    hs.application.launchOrFocus("Obsidian")
end)
hs.hotkey.bind(SA, "N", function()
    hs.application.launchOrFocus("Notion")
end)
hs.hotkey.bind("alt", "M", function()
    hs.application.launchOrFocus("Music")
end)
hs.hotkey.bind(SA, "E", function()
    hs.application.launchOrFocus("Mail")
end)
hs.hotkey.bind("alt", "x", function()
    hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind(SA, "F", function()
    hs.application.launchOrFocus("Finder")
end)
