;;; doom-catppuccin-mocha.el --- Catppuccin (Mocha) for Doom Emacs -*- lexical-binding: t; -*-
;; Generated by assistant
(require 'doom-themes)

(def-doom-theme doom-catppuccin-mocha
  "Catppuccin Mocha theme ported to Doom Emacs with extra faces."

  ;; name      default   256       16
  (
   (bg         '("#1e1e2e" "black"       "black"))
   (bg-alt     '("#181825" "black"       "black"))
   (base0      '("#181825" "black"       "black"))
   (base1      '("#313244" "brightblack" "brightblack"))
   (base2      '("#45475a" "brightblack" "brightblack"))
   (base3      '("#585b70" "brightblack" "brightblack"))
   (base4      '("#6c7086" "brightblack" "brightblack"))
   (base5      '("#7f849c" "brightblack" "brightblack"))
   (base6      '("#9399b2" "brightblack" "brightblack"))
   (base7      '("#a6adc8" "brightblack" "brightblack"))
   (base8      '("#bac2de" "white"       "white"))
   (fg         '("#cdd6f4" "white"       "white"))
   (fg-alt     '("#bac2de" "white"       "white"))

   ;; Colors
   (rosewater  '("#f5e0dc" "red" "red"))
   (flamingo   '("#f2cdcd" "magenta" "magenta"))
   (pink       '("#f5c2e7" "magenta" "magenta"))
   (mauve      '("#cba6f7" "magenta" "magenta"))
   (red        '("#f38ba8" "red" "red"))
   (maroon     '("#eba0ac" "red" "red"))
   (peach      '("#fab387" "orange" "orange"))
   (yellow     '("#f9e2af" "yellow" "yellow"))
   (green      '("#a6e3a1" "green" "green"))
   (teal       '("#94e2d5" "cyan" "cyan"))
   (sky        '("#89dceb" "cyan" "cyan"))
   (sapphire   '("#74c7ec" "blue" "blue"))
   (blue       '("#89b4fa" "blue" "blue"))
   (lavender   '("#b4befe" "magenta" "magenta"))
   (text       '("#cdd6f4" "white" "white"))
   (subtext1   '("#bac2de" "white" "white"))
   (subtext0   '("#a6adc8" "white" "white"))
   (overlay2   '("#9399b2" "white" "white"))
   (overlay1   '("#7f849c" "white" "white"))
   (overlay0   '("#6c7086" "white" "white"))
   (surface2   '("#585b70" "white" "white"))
   (surface1   '("#45475a" "white" "white"))
   (surface0   '("#313244" "white" "white"))
   (base       '("#1e1e2e" "black" "black"))
   (mantle     '("#181825" "black" "black"))

  ;; Face categories
  (
   (highlight      base5)
   (vertical-bar   base1)
   (selection      base2)
   (builtin        mauve)
   (comments       overlay2)
   (doc-comments   (doom-lighten overlay2 0.18))
   (constants      lavender)
   (functions      blue)
   (keywords       mauve)
   (methods        teal)
   (operators      red)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        peach)
   (region         base3)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    peach)
   (vc-added       green)
   (vc-deleted     red)
  )

  ;; Extra faces
  (
;; Extra faces from Catppuccin (Mocha) - comprehensive set
;; Org
(org-level-1 :foreground blue :weight bold :height 1.3)
(org-level-2 :foreground mauve :weight bold :height 1.15)
(org-level-3 :foreground sky :weight bold)
(org-level-4 :foreground peach)
(org-link :foreground sapphire :underline t)
(org-block :background base1 :extend t)
(org-block-begin-line :background base1 :foreground overlay1 :slant italic)
(org-block-end-line :background base1 :foreground overlay1 :slant italic)
(org-quote :background base1 :slant italic)
(org-verbatim :foreground teal :background base2)
(org-special-keyword :foreground mauve)
(org-meta-line :foreground overlay0)

;; Modeline / Doom modeline
(mode-line :background base2 :foreground fg :box (:line-width -1 :style released-button))
(mode-line-inactive :background base1 :foreground base5 :box (:line-width -1 :style released-button))
(doom-modeline-bar :background blue)
(doom-modeline-info :foreground blue)
(doom-modeline-warning :foreground yellow)
(doom-modeline-urgent :foreground red)
(doom-modeline-debug :foreground mauve)

;; Line numbers
(line-number :foreground base5)
(line-number-current-line :foreground fg :weight bold)

;; Completion / company / ivy / selectrum
(company-tooltip :background base1 :foreground fg)
(company-tooltip-selection :background base2 :foreground fg)
(ivy-current-match :background base2 :foreground fg)
(ivy-minibuffer-match-face-1 :foreground mauve)
(ivy-minibuffer-match-face-2 :foreground blue)

;; Syntax highlighting (font-lock)
(font-lock-builtin-face :foreground magenta)
(font-lock-comment-face :foreground overlay2 :slant italic)
(font-lock-constant-face :foreground violet)
(font-lock-function-name-face :foreground blue :weight bold)
(font-lock-keyword-face :foreground mauve :weight bold)
(font-lock-string-face :foreground green)
(font-lock-variable-name-face :foreground fg)
(font-lock-type-face :foreground yellow)
(font-lock-warning-face :foreground peach :weight bold)

;; UI
(fringe :background base)
(vertical-border :foreground base4)
(cursor :background mauve)
(region :background base3 :extend t)
(highlight :background base2)
(link :foreground sapphire :underline t)
(button :background base1 :foreground fg)

;; Search
(isearch :background yellow :foreground base)
(lazy-highlight :background base2 :foreground fg)

;; Git / VC
(git-commit-summary :foreground fg)
(magit-section-heading :foreground blue :weight bold)
(magit-hunk-heading :background base1)
(magit-diff-added :foreground green)
(magit-diff-removed :foreground red)
(vc-edited-state :foreground peach)

;; Flycheck / Flymake
(flycheck-error :underline (:style wave :color red))
(flycheck-warning :underline (:style wave :color yellow))
(flycheck-info :underline (:style wave :color blue))

;; Minibuffer / prompt
(minibuffer-prompt :foreground blue :weight bold)

;; Term / ANSI colors mapping
(ansi-color-black :foreground base)
(ansi-color-red :foreground red)
(ansi-color-green :foreground green)
(ansi-color-yellow :foreground yellow)
(ansi-color-blue :foreground blue)
(ansi-color-magenta :foreground mauve)
(ansi-color-cyan :foreground teal)
(ansi-color-white :foreground fg)

;; Misc popular packages
(which-key-command-description-face :foreground fg)
(which-key-key-face :foreground blue)
(swiper-match-face-1 :foreground mauve)
(swiper-match-face-2 :foreground blue)

;; Tree / Sidebar
(neo-root-dir-face :foreground blue)
(neo-dir-link-face :foreground mauve)
(neo-file-link-face :foreground fg)

;; Org-Roam / Deft / Notetaking
(deft-title-face :foreground blue :weight bold)
(org-roam-link-face :foreground sapphire :underline t)

;; Others
(tooltip :background base1 :foreground fg)
(default :background base :foreground fg)
)
  )
;;; doom-catppuccin-mocha.el ends here
